services:
  - type: worker
    name: instagram-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py  # Changed from bot.py to main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
